trigger: none

pr: 
  - master

resources:
  repositories:
    - repository: templates
      type: github
      name: hmcts/azure-devops-templates
      ref: refs/heads/master 
      endpoint: hmcts

parameters:
  - name: environment
    displayName: "Release To"
    type: string
    default: sbox
    values:
    - sbox
    - dev
    - test
    - ithc

variables:
  - group: vh-perf-test

stages:

- stage: Validate_Terraform_Code
  displayName: 'Validate Terraform Code'
  jobs:
    - job: Validate_Terraform_Code
      displayName: Validate Terraform Code
      steps:
      - template: pipeline/terraform-validate.yaml
        parameters:
          tfversion: $[variables.tfversion]
          workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'

- stage: Plan_Terraform_Code
  displayName: 'Plan Terraform Code'
  jobs:
    - job:
      steps:
      - template: pipeline/terraform-plan.yaml
        parameters:
          environment: ${{ parameters.environment }}
          location: ${{ variables.location }}
          project: ${{ variables.project }}
          product: ${{ variables.product }}
          builtFrom: $(Build.Repository.Name)
          tfversion: ${{ variables.terraformVersion }}
          workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
          serviceConnection: DTS-SHAREDSERVICES-${{ parameters.environment }}-Video Hearings
          tfStateResourceGroup: vh-infra-core-${{ parameters.environment }}-tf
          tfStateStorageAccountName: vhinfracore${{ parameters.environment }}tf